version: '3.7'

services:
  backend:
    image: mraarif/capstone-backend
    build:
      context: ./backend
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: mongo:4.4
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
        - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

  frontend:
    image: mraarif/capstone-frontend
    build:
      context: ./frontend
      args:
        BACKEND_IP: ${BACKEND_IP}
    volumes:
      - './frontend/:/usr/src/frontend'
      - '/usr/src/frontend/node_modules'
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  postgres_data: