version: '3.7'

services:
  backend:
    image: mraarif/fashion-index-backend
    container_name: fashion-index-backend
    build:
      context: ./backend
    volumes:
      - ./backend/:/opt/services/djangoapp/src
    ports:
      - "8080:80"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: mongo:4.4
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
        - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  frontend:
    image: mraarif/fashion-index-frontend
    build:
      context: ./frontend
      args:
        BACKEND_API_URL: ${BACKEND_API_URL}
    volumes:
      - './frontend/:/opt/services/fashion-index/src'
      - './frontend/:/opt/services/fashion-index/src/node_modules'
    ports:
      - "80:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  mongodb_data: